anothr FT

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -257,9 +257,14 @@ jobs:
       with:
         xcode-version: latest
 
+    - name: Setup CMake
+      uses: lukka/get-cmake@v4
+      with:
+        cmakeVersion: 3.31.7
+
     - name: Install Build Dependencies
       run: |
-        brew install cmake meson pkg-config llvm spirv-tools spirv-llvm-translator libclc
+        brew install meson pkg-config llvm spirv-tools spirv-llvm-translator libclc
         pip3 install --break-system-packages mako packaging pyyaml
     - name: Cache CMake Configuration
       uses: actions/cache@v5.0.4
@@ -285,9 +290,14 @@ jobs:
     - name: Print CPU Info
       run: sysctl hw machdep.cpu
 
+    - name: Setup CMake
+      uses: lukka/get-cmake@v4
+      with:
+        cmakeVersion: 3.31.7
+
     - name: Install Build Dependencies
       run: |
-        brew install cmake meson pkg-config llvm spirv-tools spirv-llvm-translator libclc
+        brew install meson pkg-config llvm spirv-tools spirv-llvm-translator libclc
         pip3 install --break-system-packages mako packaging pyyaml
 
     - name: Configure CMake
@@ -300,9 +310,9 @@ jobs:
       run: |
         mkdir upload
         mv ${{github.workspace}}/build/shadps4 upload
-        mv ${{github.workspace}}/build/libvulkan.dylib upload
-        mv ${{github.workspace}}/build/libvulkan_kosmickrisp.dylib upload
-        mv ${{github.workspace}}/build/kosmickrisp_mesa_icd.json upload
+        [ -f "${{github.workspace}}/build/libvulkan.dylib" ] && mv ${{github.workspace}}/build/libvulkan.dylib upload || echo "libvulkan.dylib not found"
+        [ -f "${{github.workspace}}/build/libvulkan_kosmickrisp.dylib" ] && mv ${{github.workspace}}/build/libvulkan_kosmickrisp.dylib upload || echo "libvulkan_kosmickrisp.dylib not found"
+        [ -f "${{github.workspace}}/build/kosmickrisp_mesa_icd.json" ] && mv ${{github.workspace}}/build/kosmickrisp_mesa_icd.json upload || echo "kosmickrisp_mesa_icd.json not found"
     - uses: actions/upload-artifact@v7
       with:
         name: shadps4-macos-sdl-${{ needs.get-info.outputs.date }}-${{ needs.get-info.outputs.shorthash }}
@@ -321,9 +331,14 @@ jobs:
       with:
         xcode-version: latest
 
+    - name: Setup CMake
+      uses: lukka/get-cmake@v4
+      with:
+        cmakeVersion: 3.31.7
+
     - name: Install Build Dependencies
       run: |
-        brew install cmake meson pkg-config llvm spirv-tools spirv-llvm-translator libclc
+        brew install meson pkg-config llvm spirv-tools spirv-llvm-translator libclc
         pip3 install --break-system-packages mako packaging pyyaml
 
     - name: Setup Qt
